version: '3'

services:
  ui:
    container_name: ui
    build:
      context: ./
      target: staging
    ports:
      - '3000:3000'
    volumes:
      - '/usr/src/app/node_modules'
      - '.:/usr/src/app'

networks: 
  default:
    name: app-visium-network