version: '3'

services:
  ui:
    container_name: app-ui
    build:
      context: ./
      target: prod
    ports:
      - '80:80'
    volumes:
      - '.:/usr/src/app'

networks: 
  default:
    name: app-visium-network